#!/bin/bash

# Script para renomear arquivos com emojis para compatibilidade com Windows
# Preserva o histórico do Git usando 'git mv'

set -e  # Parar se houver erro

echo "🔧 Iniciando renomeação de arquivos com emojis..."
echo ""

# Contador de arquivos renomeados
count=0

# Função para renomear arquivo
rename_file() {
    local old_path="$1"
    local new_path="$2"
    
    if [ -f "$old_path" ]; then
        echo "  Renomeando: $old_path"
        echo "         → $new_path"
        git mv "$old_path" "$new_path"
        ((count++))
    else
        echo "  ⚠️  Arquivo não encontrado: $old_path"
    fi
}

echo "📁 Processando arquivos na raiz do projeto..."
echo ""

# Raiz do projeto
rename_file "🎊_INICIO_RAPIDO.txt" "[INICIO]_INICIO_RAPIDO.txt"
rename_file "🎊_PLANO_EXECUTADO_COM_SUCESSO.md" "[SUCESSO]_PLANO_EXECUTADO_COM_SUCESSO.md"
rename_file "🎯_ACAO_REQUERIDA_OAUTH_GOOGLE.md" "[ACAO]_ACAO_REQUERIDA_OAUTH_GOOGLE.md"
rename_file "🚀_INICIO_RAPIDO_GOOGLE_API.md" "[RAPIDO]_INICIO_RAPIDO_GOOGLE_API.md"
rename_file "▶️_COMECE_AQUI.md" "[START]_COMECE_AQUI.md"
rename_file "▶️_COMECE_AQUI_GOOGLE.md" "[START]_COMECE_AQUI_GOOGLE.md"
rename_file "▶️_LEIA_PRIMEIRO_GOOGLE.md" "[START]_LEIA_PRIMEIRO_GOOGLE.md"
rename_file "⚠️_REPOSITORIO_NAO_EXISTE.md" "[AVISO]_REPOSITORIO_NAO_EXISTE.md"
rename_file "⚠️_STATUS_THUMBNAILS_PSD.md" "[AVISO]_STATUS_THUMBNAILS_PSD.md"
rename_file "⚡_COMANDOS_FINAIS_GOOGLE.sh" "[URGENTE]_COMANDOS_FINAIS_GOOGLE.sh"
rename_file "⚡_COMANDOS_RAPIDOS.sh" "[URGENTE]_COMANDOS_RAPIDOS.sh"
rename_file "⚡_CONFIGURAR_SEM_JSON.md" "[URGENTE]_CONFIGURAR_SEM_JSON.md"
rename_file "✅_APROVACAO_PR_COMPLETA.md" "[OK]_APROVACAO_PR_COMPLETA.md"
rename_file "✅_CHECKLIST_FUNCIONALIDADES.md" "[OK]_CHECKLIST_FUNCIONALIDADES.md"
rename_file "✅_CORRECAO_THUMBNAILS_PSD_GRANDES.md" "[OK]_CORRECAO_THUMBNAILS_PSD_GRANDES.md"
rename_file "✅_CORRECOES_APLICADAS_CACHE.md" "[OK]_CORRECOES_APLICADAS_CACHE.md"
rename_file "✅_CORRECOES_FINAIS_MCP.md" "[OK]_CORRECOES_FINAIS_MCP.md"
rename_file "✅_GITHUB_ACTIONS_FUNCIONANDO.md" "[OK]_GITHUB_ACTIONS_FUNCIONANDO.md"
rename_file "✅_IMPORTACAO_VAGARO_COMPLETA.md" "[OK]_IMPORTACAO_VAGARO_COMPLETA.md"
rename_file "✅_MERGE_CONCLUIDO_SUCESSO.md" "[OK]_MERGE_CONCLUIDO_SUCESSO.md"
rename_file "✅_RESUMO_CORRECOES_MCP.md" "[OK]_RESUMO_CORRECOES_MCP.md"
rename_file "✅_RESUMO_FINAL.md" "[OK]_RESUMO_FINAL.md"
rename_file "✅_SISTEMA_100%_FUNCIONAL.md" "[OK]_SISTEMA_100_PORCENTO_FUNCIONAL.md"
rename_file "✅_SISTEMA_TESTADO_E_FUNCIONANDO.md" "[OK]_SISTEMA_TESTADO_E_FUNCIONANDO.md"
rename_file "✅_SISTEMA_THUMBNAILS_UNIVERSAL_IMPLEMENTADO.md" "[OK]_SISTEMA_THUMBNAILS_UNIVERSAL_IMPLEMENTADO.md"
rename_file "✅_TODOS_COMPLETADOS.md" "[OK]_TODOS_COMPLETADOS.md"
rename_file "✅_VERIFICACAO_COMPLETA_BRANCHES.md" "[OK]_VERIFICACAO_COMPLETA_BRANCHES.md"
rename_file "✅_VERIFICACAO_FINAL_CONCLUSAO.md" "[OK]_VERIFICACAO_FINAL_CONCLUSAO.md"
rename_file "🆘_GUIA_TROUBLESHOOTING_MCP.md" "[AJUDA]_GUIA_TROUBLESHOOTING_MCP.md"
rename_file "🎉_CREDENCIAIS_GOOGLE_COMPLETAS.md" "[SUCESSO]_CREDENCIAIS_GOOGLE_COMPLETAS.md"
rename_file "🎉_IMPLEMENTACAO_COMPLETA.md" "[SUCESSO]_IMPLEMENTACAO_COMPLETA.md"
rename_file "🎉_IMPORTACAO_COMPLETA.md" "[SUCESSO]_IMPORTACAO_COMPLETA.md"
rename_file "🎉_MISSAO_COMPLETA_VAGARO.md" "[SUCESSO]_MISSAO_COMPLETA_VAGARO.md"
rename_file "🎉_RESULTADO_TESTE_WORKFLOWS.md" "[SUCESSO]_RESULTADO_TESTE_WORKFLOWS.md"
rename_file "🎉_TESTES_CONCLUIDOS_COM_SUCESSO.md" "[SUCESSO]_TESTES_CONCLUIDOS_COM_SUCESSO.md"
rename_file "🎉_TESTES_FINALIZADOS_SUCESSO.md" "[SUCESSO]_TESTES_FINALIZADOS_SUCESSO.md"
rename_file "🎉_TUDO_PRONTO.md" "[SUCESSO]_TUDO_PRONTO.md"
rename_file "🎊_PROGRESSO_FINAL_FASE_2.md" "[INICIO]_PROGRESSO_FINAL_FASE_2.md"
rename_file "🎊_RELATORIO_VISUAL_TESTES_COMPLETO.md" "[INICIO]_RELATORIO_VISUAL_TESTES_COMPLETO.md"
rename_file "🎊_RESUMO_APROVACAO.txt" "[INICIO]_RESUMO_APROVACAO.txt"
rename_file "🎊_RESUMO_FINAL_COMPLETO.md" "[INICIO]_RESUMO_FINAL_COMPLETO.md"
rename_file "🎊_RESUMO_GITHUB_ACTIONS.txt" "[INICIO]_RESUMO_GITHUB_ACTIONS.txt"
rename_file "🎊_SISTEMA_PRONTO.md" "[INICIO]_SISTEMA_PRONTO.md"
rename_file "🎊_TESTE_CONCLUIDO.txt" "[INICIO]_TESTE_CONCLUIDO.txt"
rename_file "🎨_NOVO_VISUAL_ABAS_MELHORADO.md" "[VISUAL]_NOVO_VISUAL_ABAS_MELHORADO.md"
rename_file "🎯_BACKEND_COMPLETO.md" "[ACAO]_BACKEND_COMPLETO.md"
rename_file "🎯_GUIA_RAPIDO_VISUAL.md" "[ACAO]_GUIA_RAPIDO_VISUAL.md"
rename_file "🎯_PASSOS_FINAIS_GOOGLE_AUTH.md" "[ACAO]_PASSOS_FINAIS_GOOGLE_AUTH.md"
rename_file "🎯_PROGRESSO_VISUAL.md" "[ACAO]_PROGRESSO_VISUAL.md"
rename_file "🎯_RESUMO_RAPIDO.txt" "[ACAO]_RESUMO_RAPIDO.txt"
rename_file "🎯_RESUMO_VERIFICACAO_VISUAL.txt" "[ACAO]_RESUMO_VERIFICACAO_VISUAL.txt"
rename_file "🎯_STATUS_ATUAL_SISTEMA.md" "[ACAO]_STATUS_ATUAL_SISTEMA.md"
rename_file "🎯_STATUS_BRANCHES_RAPIDO.txt" "[ACAO]_STATUS_BRANCHES_RAPIDO.txt"
rename_file "🎯_TESTE_RAPIDO_GITHUB_ACTIONS.md" "[ACAO]_TESTE_RAPIDO_GITHUB_ACTIONS.md"
rename_file "🏆_83%_COMPLETO_PRONTO_PARA_USO.md" "[COMPLETO]_83_PORCENTO_COMPLETO_PRONTO_PARA_USO.md"
rename_file "📅_TESTE_02_CALENDARIO_VISUAL.md" "[CALENDARIO]_TESTE_02_CALENDARIO_VISUAL.md"
rename_file "📊_RELATORIO_TESTES_COMPLETO.md" "[STATUS]_RELATORIO_TESTES_COMPLETO.md"
rename_file "📊_RESUMO_TESTES_FINAL.md" "[STATUS]_RESUMO_TESTES_FINAL.md"
rename_file "📊_SISTEMA_COMPLETO_12_ABAS.md" "[STATUS]_SISTEMA_COMPLETO_12_ABAS.md"
rename_file "📊_STATUS_GITHUB_ACTIONS.md" "[STATUS]_STATUS_GITHUB_ACTIONS.md"
rename_file "📊_TESTE_01_DASHBOARD.md" "[STATUS]_TESTE_01_DASHBOARD.md"
rename_file "📋_ABAS_REORGANIZADAS_SUCESSO.md" "[LISTA]_ABAS_REORGANIZADAS_SUCESSO.md"
rename_file "📋_INDICE_COMPLETO_GOOGLE_API.md" "[LISTA]_INDICE_COMPLETO_GOOGLE_API.md"
rename_file "📋_LEIA_ISTO_VERIFICACAO_COMPLETA.md" "[LISTA]_LEIA_ISTO_VERIFICACAO_COMPLETA.md"
rename_file "📋_RESUMO_FINAL_COMPLETO.md" "[LISTA]_RESUMO_FINAL_COMPLETO.md"
rename_file "📋_RESUMO_FINAL_SISTEMA.md" "[LISTA]_RESUMO_FINAL_SISTEMA.md"
rename_file "📋_RESUMO_MERGE_BRANCHES.md" "[LISTA]_RESUMO_MERGE_BRANCHES.md"
rename_file "📋_SISTEMA_IMPORTACAO_VAGARO_COMPLETO.md" "[LISTA]_SISTEMA_IMPORTACAO_VAGARO_COMPLETO.md"
rename_file "📋_TESTE_ABA_CLIENTES_CORRIGIDA.md" "[LISTA]_TESTE_ABA_CLIENTES_CORRIGIDA.md"
rename_file "📋_VALIDACAO_COMPLETA_MAIN_BRANCH.md" "[LISTA]_VALIDACAO_COMPLETA_MAIN_BRANCH.md"
rename_file "📖_INDICE_RAPIDO.md" "[GUIA]_INDICE_RAPIDO.md"
rename_file "📝_MCP_CONFIGURACAO_CORRIGIDA.md" "[NOTA]_MCP_CONFIGURACAO_CORRIGIDA.md"
rename_file "📝_ORGANIZACAO_COMPLETA.md" "[NOTA]_ORGANIZACAO_COMPLETA.md"
rename_file "📝_TESTE_03_AGENDAMENTOS.md" "[NOTA]_TESTE_03_AGENDAMENTOS.md"
rename_file "📢_LEIA_PRIMEIRO.md" "[IMPORTANTE]_LEIA_PRIMEIRO.md"
rename_file "🔐_ATIVAR_2FA_E_BAIXAR_CREDENCIAIS.md" "[SEGURANCA]_ATIVAR_2FA_E_BAIXAR_CREDENCIAIS.md"
rename_file "🔐_CREDENCIAIS_GOOGLE_API.md" "[SEGURANCA]_CREDENCIAIS_GOOGLE_API.md"
rename_file "🔑_CHAVES_API_REFERENCIA.md" "[CHAVES]_CHAVES_API_REFERENCIA.md"
rename_file "🔧_ANTES_E_DEPOIS_MCP.md" "[CONFIG]_ANTES_E_DEPOIS_MCP.md"
rename_file "🔧_COMO_CORRIGIR_PSDs.md" "[CONFIG]_COMO_CORRIGIR_PSDs.md"
rename_file "🔧_CORRIGIR_GOOGLE_AUTH.md" "[CONFIG]_CORRIGIR_GOOGLE_AUTH.md"
rename_file "🔧_SOLUCAO_DEFINITIVA_THUMBNAILS_PSD.md" "[CONFIG]_SOLUCAO_DEFINITIVA_THUMBNAILS_PSD.md"
rename_file "🔧_TESTES_E_CORRECOES.md" "[CONFIG]_TESTES_E_CORRECOES.md"
rename_file "🔽_BAIXAR_CREDENCIAIS_AGORA.md" "[BAIXAR]_BAIXAR_CREDENCIAIS_AGORA.md"
rename_file "🧪_RELATORIO_TESTES_FRONTEND.md" "[TESTE]_RELATORIO_TESTES_FRONTEND.md"
rename_file "🧪_RELATORIO_TESTES_GOOGLE_DRIVE.md" "[TESTE]_RELATORIO_TESTES_GOOGLE_DRIVE.md"

echo ""
echo "📁 Processando arquivos em lixeira/documentacao-antiga..."
echo ""

# Pasta lixeira/documentacao-antiga
rename_file "lixeira/documentacao-antiga/▶️_COMECE_AQUI_GESTAO_CLIENTES.md" "lixeira/documentacao-antiga/[START]_COMECE_AQUI_GESTAO_CLIENTES.md"
rename_file "lixeira/documentacao-antiga/▶️_INICIO_RAPIDO.md" "lixeira/documentacao-antiga/[START]_INICIO_RAPIDO.md"
rename_file "lixeira/documentacao-antiga/⚡_ATIVAR_SISTEMA_3_PASSOS.md" "lixeira/documentacao-antiga/[URGENTE]_ATIVAR_SISTEMA_3_PASSOS.md"
rename_file "lixeira/documentacao-antiga/⚡_INICIO_RAPIDO_GESTAO_CLIENTES.md" "lixeira/documentacao-antiga/[URGENTE]_INICIO_RAPIDO_GESTAO_CLIENTES.md"
rename_file "lixeira/documentacao-antiga/⚡_RESULTADO_TESTE_NAVEGADOR.txt" "lixeira/documentacao-antiga/[URGENTE]_RESULTADO_TESTE_NAVEGADOR.txt"
rename_file "lixeira/documentacao-antiga/⚡_TESTE_AGORA_3_PASSOS_ATUALIZADO.md" "lixeira/documentacao-antiga/[URGENTE]_TESTE_AGORA_3_PASSOS_ATUALIZADO.md"
rename_file "lixeira/documentacao-antiga/✅_CALENDARIO_DIA_EXPANDIDO.md" "lixeira/documentacao-antiga/[OK]_CALENDARIO_DIA_EXPANDIDO.md"
rename_file "lixeira/documentacao-antiga/✅_IMPLEMENTACAO_COMPLETA_SUCESSO.md" "lixeira/documentacao-antiga/[OK]_IMPLEMENTACAO_COMPLETA_SUCESSO.md"
rename_file "lixeira/documentacao-antiga/✅_LAYOUT_MELHORADO.txt" "lixeira/documentacao-antiga/[OK]_LAYOUT_MELHORADO.txt"
rename_file "lixeira/documentacao-antiga/✅_PROBLEMA_SINCRONIZACAO_RESOLVIDO.md" "lixeira/documentacao-antiga/[OK]_PROBLEMA_SINCRONIZACAO_RESOLVIDO.md"
rename_file "lixeira/documentacao-antiga/✅_RELATORIO_VERIFICACAO_COMPLETA.md" "lixeira/documentacao-antiga/[OK]_RELATORIO_VERIFICACAO_COMPLETA.md"
rename_file "lixeira/documentacao-antiga/✅_RESUMO_VISUAL_CALENDARIO.md" "lixeira/documentacao-antiga/[OK]_RESUMO_VISUAL_CALENDARIO.md"
rename_file "lixeira/documentacao-antiga/✅_RESUMO_VISUAL_DIA_EXPANDIDO.txt" "lixeira/documentacao-antiga/[OK]_RESUMO_VISUAL_DIA_EXPANDIDO.txt"
rename_file "lixeira/documentacao-antiga/✅_SINCRONIZACAO_HIBRIDA_COMPLETA.md" "lixeira/documentacao-antiga/[OK]_SINCRONIZACAO_HIBRIDA_COMPLETA.md"
rename_file "lixeira/documentacao-antiga/✅_SINCRONIZACAO_IMPLEMENTADA.md" "lixeira/documentacao-antiga/[OK]_SINCRONIZACAO_IMPLEMENTADA.md"
rename_file "lixeira/documentacao-antiga/✅_SISTEMA_GESTAO_CLIENTES_100_FUNCIONAL.md" "lixeira/documentacao-antiga/[OK]_SISTEMA_GESTAO_CLIENTES_100_FUNCIONAL.md"
rename_file "lixeira/documentacao-antiga/✅_SISTEMA_INSTALADO_SUCESSO.md" "lixeira/documentacao-antiga/[OK]_SISTEMA_INSTALADO_SUCESSO.md"
rename_file "lixeira/documentacao-antiga/✅_STATUS_FINAL_GESTAO_CLIENTES.txt" "lixeira/documentacao-antiga/[OK]_STATUS_FINAL_GESTAO_CLIENTES.txt"
rename_file "lixeira/documentacao-antiga/✅_THUMBNAILS_CORRIGIDAS.md" "lixeira/documentacao-antiga/[OK]_THUMBNAILS_CORRIGIDAS.md"
rename_file "lixeira/documentacao-antiga/✅_THUMBNAILS_E_PSD_PRONTOS.md" "lixeira/documentacao-antiga/[OK]_THUMBNAILS_E_PSD_PRONTOS.md"
rename_file "lixeira/documentacao-antiga/✅_THUMBNAILS_PRONTOS.md" "lixeira/documentacao-antiga/[OK]_THUMBNAILS_PRONTOS.md"
rename_file "lixeira/documentacao-antiga/✅_UPLOAD_ATIVADO.txt" "lixeira/documentacao-antiga/[OK]_UPLOAD_ATIVADO.txt"
rename_file "lixeira/documentacao-antiga/✅_VERIFICACAO_COMPLETA_CONCLUIDA.txt" "lixeira/documentacao-antiga/[OK]_VERIFICACAO_COMPLETA_CONCLUIDA.txt"
rename_file "lixeira/documentacao-antiga/✅_VERIFICACAO_SISTEMA_SINCRONIZACAO.md" "lixeira/documentacao-antiga/[OK]_VERIFICACAO_SISTEMA_SINCRONIZACAO.md"
rename_file "lixeira/documentacao-antiga/⭐_LEIA_PRIMEIRO_RESUMO_RAPIDO.txt" "lixeira/documentacao-antiga/[ESTRELA]_LEIA_PRIMEIRO_RESUMO_RAPIDO.txt"
rename_file "lixeira/documentacao-antiga/🇧🇷_INSTALACAO_COMPLETA.md" "lixeira/documentacao-antiga/[BR]_INSTALACAO_COMPLETA.md"
rename_file "lixeira/documentacao-antiga/🇧🇷_LEIA_AQUI_PRIMEIRO.md" "lixeira/documentacao-antiga/[BR]_LEIA_AQUI_PRIMEIRO.md"
rename_file "lixeira/documentacao-antiga/🎉_CALENDARIO_COM_THUMBNAILS_GOOGLE_DRIVE.md" "lixeira/documentacao-antiga/[SUCESSO]_CALENDARIO_COM_THUMBNAILS_GOOGLE_DRIVE.md"
rename_file "lixeira/documentacao-antiga/🎉_CALENDARIO_PRONTO.md" "lixeira/documentacao-antiga/[SUCESSO]_CALENDARIO_PRONTO.md"
rename_file "lixeira/documentacao-antiga/🎉_FUNCIONALIDADES_PRONTAS.md" "lixeira/documentacao-antiga/[SUCESSO]_FUNCIONALIDADES_PRONTAS.md"
rename_file "lixeira/documentacao-antiga/🎉_NOVAS_FUNCIONALIDADES_IMPLEMENTADAS.md" "lixeira/documentacao-antiga/[SUCESSO]_NOVAS_FUNCIONALIDADES_IMPLEMENTADAS.md"
rename_file "lixeira/documentacao-antiga/🎉_RELATORIO_FINAL_IMPLEMENTACAO.md" "lixeira/documentacao-antiga/[SUCESSO]_RELATORIO_FINAL_IMPLEMENTACAO.md"
rename_file "lixeira/documentacao-antiga/🎉_SISTEMA_100_FUNCIONAL.md" "lixeira/documentacao-antiga/[SUCESSO]_SISTEMA_100_FUNCIONAL.md"
rename_file "lixeira/documentacao-antiga/🎉_SISTEMA_GESTAO_CLIENTES_INSTALADO.md" "lixeira/documentacao-antiga/[SUCESSO]_SISTEMA_GESTAO_CLIENTES_INSTALADO.md"
rename_file "lixeira/documentacao-antiga/🎉_SISTEMA_GESTAO_CLIENTES_PRONTO.md" "lixeira/documentacao-antiga/[SUCESSO]_SISTEMA_GESTAO_CLIENTES_PRONTO.md"
rename_file "lixeira/documentacao-antiga/🎉_SISTEMA_SINCRONIZACAO_PRONTO.md" "lixeira/documentacao-antiga/[SUCESSO]_SISTEMA_SINCRONIZACAO_PRONTO.md"
rename_file "lixeira/documentacao-antiga/🎉_TESTE_NAVEGADOR_COMPLETO_SUCESSO.md" "lixeira/documentacao-antiga/[SUCESSO]_TESTE_NAVEGADOR_COMPLETO_SUCESSO.md"
rename_file "lixeira/documentacao-antiga/🎊_INSTALACAO_FINALIZADA.txt" "lixeira/documentacao-antiga/[INICIO]_INSTALACAO_FINALIZADA.txt"
rename_file "lixeira/documentacao-antiga/🎊_TRABALHO_CONCLUIDO_100_PORCENTO.txt" "lixeira/documentacao-antiga/[INICIO]_TRABALHO_CONCLUIDO_100_PORCENTO.txt"
rename_file "lixeira/documentacao-antiga/🎊_TRABALHO_FINALIZADO_100_PORCENTO.txt" "lixeira/documentacao-antiga/[INICIO]_TRABALHO_FINALIZADO_100_PORCENTO.txt"
rename_file "lixeira/documentacao-antiga/🎊_TRABALHO_FINALIZADO_RESUMO_VISUAL.txt" "lixeira/documentacao-antiga/[INICIO]_TRABALHO_FINALIZADO_RESUMO_VISUAL.txt"
rename_file "lixeira/documentacao-antiga/🎯_RESULTADO_VERIFICACAO.txt" "lixeira/documentacao-antiga/[ACAO]_RESULTADO_VERIFICACAO.txt"
rename_file "lixeira/documentacao-antiga/🎯_RESUMO_EXECUTIVO_FINAL.txt" "lixeira/documentacao-antiga/[ACAO]_RESUMO_EXECUTIVO_FINAL.txt"
rename_file "lixeira/documentacao-antiga/🎯_RESUMO_EXECUTIVO_FINAL_ATUALIZADO.txt" "lixeira/documentacao-antiga/[ACAO]_RESUMO_EXECUTIVO_FINAL_ATUALIZADO.txt"
rename_file "lixeira/documentacao-antiga/🎯_RESUMO_FINAL_COMPLETO.txt" "lixeira/documentacao-antiga/[ACAO]_RESUMO_FINAL_COMPLETO.txt"
rename_file "lixeira/documentacao-antiga/🎯_RESUMO_TESTE_NAVEGADOR.txt" "lixeira/documentacao-antiga/[ACAO]_RESUMO_TESTE_NAVEGADOR.txt"
rename_file "lixeira/documentacao-antiga/🎯_RESUMO_VISUAL_INSTALACAO.txt" "lixeira/documentacao-antiga/[ACAO]_RESUMO_VISUAL_INSTALACAO.txt"
rename_file "lixeira/documentacao-antiga/🎯_STATUS_FINAL_SISTEMA.md" "lixeira/documentacao-antiga/[ACAO]_STATUS_FINAL_SISTEMA.md"
rename_file "lixeira/documentacao-antiga/🏁_STATUS_FINAL_COMPLETO.txt" "lixeira/documentacao-antiga/[FINAL]_STATUS_FINAL_COMPLETO.txt"
rename_file "lixeira/documentacao-antiga/👉_LEIA_ISTO_AGORA.md" "lixeira/documentacao-antiga/[LEIA]_LEIA_ISTO_AGORA.md"
rename_file "lixeira/documentacao-antiga/👉_LEIA_ISTO_PRIMEIRO.md" "lixeira/documentacao-antiga/[LEIA]_LEIA_ISTO_PRIMEIRO.md"
rename_file "lixeira/documentacao-antiga/📊_PROGRESSO_TESTES_COMPLETOS.md" "lixeira/documentacao-antiga/[STATUS]_PROGRESSO_TESTES_COMPLETOS.md"
rename_file "lixeira/documentacao-antiga/📊_RESULTADO_VISUAL.txt" "lixeira/documentacao-antiga/[STATUS]_RESULTADO_VISUAL.txt"
rename_file "lixeira/documentacao-antiga/📊_RESUMO_STATUS_RAPIDO.txt" "lixeira/documentacao-antiga/[STATUS]_RESUMO_STATUS_RAPIDO.txt"
rename_file "lixeira/documentacao-antiga/📋_CHECKLIST_PROXIMAS_ETAPAS.md" "lixeira/documentacao-antiga/[LISTA]_CHECKLIST_PROXIMAS_ETAPAS.md"
rename_file "lixeira/documentacao-antiga/📋_LISTA_ARQUIVOS_CRIADOS_NESTA_SESSAO.md" "lixeira/documentacao-antiga/[LISTA]_LISTA_ARQUIVOS_CRIADOS_NESTA_SESSAO.md"
rename_file "lixeira/documentacao-antiga/📌_EXPLICACAO_CURSOR_BUILD.md" "lixeira/documentacao-antiga/[PIN]_EXPLICACAO_CURSOR_BUILD.md"
rename_file "lixeira/documentacao-antiga/📚_INDICE_COMPLETO_DOCUMENTACAO.md" "lixeira/documentacao-antiga/[INDICE]_INDICE_COMPLETO_DOCUMENTACAO.md"
rename_file "lixeira/documentacao-antiga/📚_INDICE_DOCUMENTACAO_COMPLETA.md" "lixeira/documentacao-antiga/[INDICE]_INDICE_DOCUMENTACAO_COMPLETA.md"
rename_file "lixeira/documentacao-antiga/📚_INDICE_GESTAO_CLIENTES.md" "lixeira/documentacao-antiga/[INDICE]_INDICE_GESTAO_CLIENTES.md"
rename_file "lixeira/documentacao-antiga/📦_ARQUIVOS_CRIADOS.md" "lixeira/documentacao-antiga/[PACOTE]_ARQUIVOS_CRIADOS.md"
rename_file "lixeira/documentacao-antiga/📦_SUMARIO_FINAL_ENTREGA.md" "lixeira/documentacao-antiga/[PACOTE]_SUMARIO_FINAL_ENTREGA.md"
rename_file "lixeira/documentacao-antiga/🔧_CORRIGIR_GOOGLE_AUTH.md" "lixeira/documentacao-antiga/[CONFIG]_CORRIGIR_GOOGLE_AUTH.md"
rename_file "lixeira/documentacao-antiga/🚀_INICIO_RAPIDO.md" "lixeira/documentacao-antiga/[RAPIDO]_INICIO_RAPIDO.md"
rename_file "lixeira/documentacao-antiga/🚀_INICIO_RAPIDO.txt" "lixeira/documentacao-antiga/[RAPIDO]_INICIO_RAPIDO.txt"
rename_file "lixeira/documentacao-antiga/🧪_RELATORIO_COMPLETO_TESTES_NAVEGADOR.md" "lixeira/documentacao-antiga/[TESTE]_RELATORIO_COMPLETO_TESTES_NAVEGADOR.md"

echo ""
echo "✅ Renomeação concluída!"
echo "📊 Total de arquivos renomeados: $count"
echo ""

