name: Auto Label - Labels Automáticos

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    label:
        name: Aplicar Labels Automáticos
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Apply Labels
              uses: actions/labeler@v5
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
                  sync-labels: true
