name: Security Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security checks weekly on Monday at 9 AM
    - cron: '0 9 * * 1'

jobs:
  # Dependency vulnerability scan
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install backend dependencies
        run: |
          cd agenda-hibrida-v2
          npm ci
      
      - name: Install frontend dependencies
        run: |
          cd agenda-hibrida-frontend
          npm ci
      
      - name: Run npm audit on backend
        run: |
          cd agenda-hibrida-v2
          npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Run npm audit on frontend
        run: |
          cd agenda-hibrida-frontend
          npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Check for outdated packages
        run: |
          echo "Backend outdated packages:"
          cd agenda-hibrida-v2
          npm outdated || true
          echo "Frontend outdated packages:"
          cd ../agenda-hibrida-frontend
          npm outdated || true

  # Secret scanning
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for exposed credentials
        run: |
          echo "Checking for exposed credentials..."
          # Check for common patterns
          if grep -r "GOOGLE_CLIENT_SECRET\s*=\s*['\"]" --include="*.js" --include="*.ts" .; then
            echo "❌ Found hardcoded credentials!"
            exit 1
          fi
          echo "✅ No hardcoded credentials found"

  # Code security analysis
  code-security:
    name: Code Security Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Security summary
  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [dependency-scan, secret-scan, code-security]
    if: always()
    
    steps:
      - name: Security check summary
        run: |
          echo "Security Checks Summary:"
          echo "Dependency Scan: ${{ needs.dependency-scan.result }}"
          echo "Secret Scan: ${{ needs.secret-scan.result }}"
          echo "Code Security: ${{ needs.code-security.result }}"
      
      - name: Fail if critical issues found
        if: |
          needs.dependency-scan.result == 'failure' ||
          needs.secret-scan.result == 'failure' ||
          needs.code-security.result == 'failure'
        run: |
          echo "❌ Critical security issues found!"
          exit 1

