name: Tests and Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Backend Tests
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: agenda-hibrida-v2/package-lock.json
      
      - name: Install backend dependencies
        run: |
          cd agenda-hibrida-v2
          npm ci
      
      - name: Run backend unit tests
        run: |
          cd agenda-hibrida-v2
          npm run test:unit
      
      - name: Run backend integration tests
        run: |
          cd agenda-hibrida-v2
          npm run test:integration
      
      - name: Upload backend test coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./agenda-hibrida-v2/coverage/coverage-final.json
          flags: backend
          name: backend-coverage

  # Frontend Tests
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: agenda-hibrida-frontend/pnpm-lock.yaml
      
      - name: Install frontend dependencies
        run: |
          cd agenda-hibrida-frontend
          pnpm install --frozen-lockfile
      
      - name: Lint frontend code
        run: |
          cd agenda-hibrida-frontend
          pnpm run lint
      
      - name: Build frontend
        run: |
          cd agenda-hibrida-frontend
          pnpm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: agenda-hibrida-frontend/dist
          retention-days: 7

  # E2E Tests
  e2e-tests:
    name: E2E Tests with Playwright
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install backend dependencies
        run: |
          cd agenda-hibrida-v2
          npm ci
      
      - name: Install frontend dependencies
        run: |
          cd agenda-hibrida-frontend
          pnpm install --frozen-lockfile
      
      - name: Install Playwright browsers
        run: |
          cd agenda-hibrida-frontend
          pnpm exec playwright install --with-deps chromium
      
      - name: Run E2E tests
        run: |
          cd agenda-hibrida-frontend
          pnpm run test:e2e
        env:
          CI: true
      
      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: agenda-hibrida-frontend/playwright-report
          retention-days: 7
      
      - name: Upload E2E screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: agenda-hibrida-frontend/test-results
          retention-days: 7

  # Code Quality
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install backend dependencies
        run: |
          cd agenda-hibrida-v2
          npm ci
      
      - name: Install frontend dependencies
        run: |
          cd agenda-hibrida-frontend
          pnpm install --frozen-lockfile
      
      - name: Run ESLint on backend
        run: |
          cd agenda-hibrida-v2
          npm run lint || true
      
      - name: Run ESLint on frontend
        run: |
          cd agenda-hibrida-frontend
          pnpm run lint
      
      - name: Check for security vulnerabilities
        run: |
          cd agenda-hibrida-v2
          npm audit --audit-level=high || true
          cd ../agenda-hibrida-frontend
          pnpm audit --audit-level=high || true

  # Build Status Summary
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, e2e-tests, code-quality]
    if: always()
    
    steps:
      - name: Check build status
        run: |
          echo "Build Summary:"
          echo "Backend Tests: ${{ needs.backend-tests.result }}"
          echo "Frontend Tests: ${{ needs.frontend-tests.result }}"
          echo "E2E Tests: ${{ needs.e2e-tests.result }}"
          echo "Code Quality: ${{ needs.code-quality.result }}"
      
      - name: Fail if any job failed
        if: |
          needs.backend-tests.result == 'failure' ||
          needs.frontend-tests.result == 'failure' ||
          needs.e2e-tests.result == 'failure' ||
          needs.code-quality.result == 'failure'
        run: exit 1

